### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by filenkoB** [filenkoB/homepage#6]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Marsichek2** [comment]
Hello! I am Elon Musk - theTechnoking of Tesla, Imperator of Mars! I like rockets and space and want to become the first human on Mars. I am a very cheerful guy and also can use drugs during interviews (remember, drugs are bad and do not use them if you are not the Emperor of Mars and whole Space!). Follow me and let`s conquer the unknown! ^_^

**Comment by filenkoB** [comment]
Good intro!
