### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by filenkoB** [filenkoB/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Marsichek2** [comment]
Twitter: https://twitter.com/elonmusk
Instagram: https://www.instagram.com/elonmusk/?hl=en
Facebook: https://www.facebook.com/Elon-Musk-19958149870/
Tesla website: https://www.facebook.com/Elon-Musk-19958149870/

**Comment by filenkoB** [comment]
Great! That is what we needed
